"""Generate cipher R0/Ri golden vectors from the reference model.

The oracle is :mod:`netv2.hdcp.cipher` (the reviewed HDCP 1.4 model).  For each
(Km, An) pair this emits the model's R0 (from ``authenticate``) and its Ri at
frames 128 and 256 (from repeated ``rekey_frame``), used by ``tb_cipher_rx.v``
(via ``$readmemh``) and re-checked by ``run_cipher_rx.py``.

Outputs, under ``tests/sim/hdcp/``:
  * ``cipher_vectors.hex``  -- 5 hex tokens per vector (Km, An, R0, Ri128,
    Ri256), for the testbench's ``$readmemh``.
  * ``cipher_vectors.json`` -- the same data plus metadata, for the driver.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from netv2.hdcp.cipher import HDCPCipher

# (name, Km, An).  These are THROWAWAY test Km values, NOT the shared-rig Km.
# The cipher/controller tests only verify RTL == oracle for whatever Km is
# supplied, so any value exercises them; the real rig Km is a shared secret and
# is never committed (it is computed at runtime from the gitignored sink keys by
# the key-loading tests run_hdcp_rx_km.py / run_hdcp_rx_top.py).
VECTORS = [
    ("test0", 0x00C0FFEE0D15EA, 0x34271C130C070403),
    ("fixed", 0x0123456789ABCD, 0xFEDCBA9876543210),
    ("tableA3", 0xA423D78B8676A7, 0x0351F7175406A74D),
]

FRAMES = (128, 256)


def compute(km: int, an: int) -> dict:
    """Run the oracle for one (Km, An): R0 and per-frame Ri at 128 and 256."""
    c = HDCPCipher(repeater=0)
    ks, m0, r0 = c.authenticate(km, an)
    ri = {}
    for frame in range(1, max(FRAMES) + 1):
        c.rekey_frame()
        if frame in FRAMES:
            ri[frame] = c.ri_frame
    return {
        "km": km,
        "an": an,
        "ks": ks,
        "m0": m0,
        "r0": r0,
        "ri128": ri[128],
        "ri256": ri[256],
    }


def main() -> int:
    results = []
    for name, km, an in VECTORS:
        r = compute(km, an)
        r["name"] = name
        results.append(r)

    hex_path = HERE / "cipher_vectors.hex"
    with hex_path.open("w") as f:
        f.write("// Km An R0 Ri128 Ri256 per vector -- generated by "
                "gen_cipher_vectors.py; do not edit by hand.\n")
        for r in results:
            f.write(f"{r['km']:014x} {r['an']:016x} {r['r0']:04x} "
                    f"{r['ri128']:04x} {r['ri256']:04x}  // {r['name']}\n")

    json_path = HERE / "cipher_vectors.json"
    with json_path.open("w") as f:
        json.dump({
            "note": "Golden R0/Ri from netv2.hdcp.cipher (the oracle).",
            "frames": list(FRAMES),
            "vectors": [
                {
                    "name": r["name"],
                    "km": f"{r['km']:014x}",
                    "an": f"{r['an']:016x}",
                    "r0": f"{r['r0']:04x}",
                    "ri128": f"{r['ri128']:04x}",
                    "ri256": f"{r['ri256']:04x}",
                }
                for r in results
            ],
        }, f, indent=2)
        f.write("\n")

    for r in results:
        print(f"vector {r['name']:<8} Km={r['km']:014x} An={r['an']:016x} "
              f"R0={r['r0']:04x} Ri128={r['ri128']:04x} Ri256={r['ri256']:04x}")
    print(f"wrote {hex_path}")
    print(f"wrote {json_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
