#!/usr/bin/env python3
"""
NeTV2 modern HDMI-input SoC (phase 7a).

Extends the phase-2 :class:`NeTV2BaseSoC` (VexRiscv + UART + DDR3 on LiteX
2026.04) with ONE ported litevideo HDMI **input** pipeline on the board's
``hdmi_in`` 0 connector (the "source" input on the 2019 NeTV2).

Why a litevideo port and not ``VideoS7HDMIPHY``: the goal's HDMI-audio
(de-embed/embed) work needs the HDMI **data-island** (TERC4) packets. The
modern LiteX video cores are DVI-style (pixels only) and drop data islands.
bunnie's litevideo fork keeps a raw-mode HDMI-input pipeline with a TERC4
decoder, so HDMI audio must be built on that. This target is the foundation:
it proves the ported input pipeline elaborates and that the recovered
148.5 MHz / 742.5 MHz serdes clocking closes timing on the a7-100. No audio,
no overlay, no output -- just clock/lock, resolution, and the TERC4
data-island evidence (packet / char counters + BCH capture) over CSRs.

The port lives under ``netv2/gateware/video/input/`` and the three Xilinx
phase-alignment blackboxes (``chnlbond``, ``phsaligner``, ``delay_controller``)
under ``netv2/gateware/video/blackboxes/``.

Elaborate (no build):

    uv run python -m netv2.targets.hdmi_in --variant a7-100

Build (one Vivado at a time):

    uv run python -m netv2.targets.hdmi_in --variant a7-100 --build --toolchain vivado

Outputs land under ``build/netv2-hdmi-in/``.
"""

import os

from migen import ClockSignal

from litex.build.parser import LiteXArgumentParser
from litex.soc.integration.builder import Builder
from litex.soc.cores.freqmeter import FreqMeter
from litex_boards.platforms import kosagi_netv2

from netv2.targets.base import NeTV2BaseSoC
from netv2.gateware.video.input import HDMIIn

REPO_ROOT   = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DEFAULT_OUT = os.path.join(REPO_ROOT, "build", "netv2-hdmi-in")
BLACKBOX_DIR = os.path.join(REPO_ROOT, "netv2", "gateware", "video", "blackboxes")

# The recovered HDMI-input clock tree (litevideo S7Clocking, MMCME2_ADV):
#   pix       = 148.5 MHz  (pixel clock, BUFG)
#   pix5x     = 742.5 MHz  (5x serdes bit clock, BUFIO)
#   pix1p25x  = 185.625 MHz (gearbox BUFG leg)
#   pix1p25x_r= 185.625 MHz (BUFR /4 of 742.5, serdes CLKDIV / logic)
# All are generated by the input MMCM from the ~148.5 MHz recovered link clock.
HDMI_IN_PIX_FREQ = 148.5e6


class NeTV2HDMIInSoC(NeTV2BaseSoC):
    """NeTV2 base SoC + one ported litevideo HDMI input (input0, TERC4 path).

    Instantiates :class:`HDMIIn` in the ``hdmi=True`` (TERC4 preamble DE),
    ``alt_delay=True`` (chnlbond/phsaligner/delay_controller phase alignment),
    ``dram_port=None`` (no framebuffer capture -- decode + island counters only)
    configuration used by the 2019 design's source input. Reuses the base
    CRG's single global ``IDELAYCTRL`` (200 MHz ``cd_idelay``), so the input
    IDELAYE2 delay taps reference the same 200 MHz clock: ``iodelay_clk_freq``
    is pinned to 200e6 to match.
    """
    def __init__(self, variant="a7-100", sys_clk_freq=100e6,
                 hdmi_in_cable="pcb", **kwargs):
        super().__init__(variant=variant, sys_clk_freq=sys_clk_freq, **kwargs)
        platform = self.platform

        # HDMI input pads (kosagi_netv2 platform resource: clk/data0-2 diff
        # pairs + scl/sda for the EDID I2C slave). The 2019 "source" input is
        # hdmi_in 0.
        hdmi_in_pads = platform.request("hdmi_in", 0)

        # Blackbox Verilog for the alt_delay phase-alignment path.
        # chnlbond.v instantiates DRAM16XN (a distributed-RAM delay line), so it
        # must be compiled in too.
        for v in ("DRAM16XN.v", "chnlbond.v", "phsaligner.v", "delay_controller.v"):
            platform.add_source(os.path.join(BLACKBOX_DIR, v))

        # The ported litevideo input pipeline.
        #  - hdmi=True       : TERC4 preamble-based DE + the DecodeTERC4 island decoder
        #  - alt_delay=True  : use the Verilog phsaligner/chnlbond aligners (as in 2019)
        #  - split_mmcm=False: no derived output (pix_o/pix5x_o) domain -- input only
        #  - dram_port=None  : no framebuffer DMA -- decode + island counters only
        #  - iodelay_clk_freq=200e6 : match the base CRG's 200 MHz IDELAYCTRL
        self.hdmi_in0 = HDMIIn(
            hdmi_in_pads,
            dram_port        = None,
            device           = "xc7",
            hdmi             = True,
            split_mmcm       = False,
            alt_delay        = True,
            clkin_freq       = HDMI_IN_PIX_FREQ,
            iodelay_clk_freq = 200e6,
        )
        clocking = self.hdmi_in0.clocking

        # Measured input pixel clock. Clocked from cd_pix_raw (the raw IBUFDS
        # output, valid even before the MMCM locks) exactly like the 2019
        # design, so a frequency reading is available during bring-up.
        self.hdmi_in0_freq = FreqMeter(
            period = int(sys_clk_freq),
            clk    = ClockSignal("pix_raw"),
        )

        # Timing constraints for the recovered clock tree.
        #
        # Constrain the recovered HDMI-input clock at the *input port* (the
        # clk_p pin of the TMDS pair, feeding the IBUFDS -> input MMCM). This
        # is the robust anchor -- an internal-net create_clock gets renamed by
        # synthesis (get_nets misses it). Vivado then auto-derives the MMCM/BUFR
        # output clocks (pix / pix5x / pix1p25x / pix1p25x_r) as one synchronous
        # generated-clock family, so the intra-family crossings (the 8->10
        # gearbox pix1p25x->pix, the ISERDESE2 CLK/CLKDIV pix5x/pix1p25x_r) are
        # analysed with their true phase relationship rather than as unrelated
        # clocks. This is the path whose closure (742.5 MHz serdes) is the point
        # of this build.
        platform.add_period_constraint(hdmi_in_pads.clk_p,
                                       1e9 / HDMI_IN_PIX_FREQ)

        # The following constraints reference generated clocks and internal
        # clock nets that only exist *after* synthesis. LiteX reads the .xdc
        # once, before synth (PROCESSING_ORDER EARLY), so they must be emitted
        # as pre-placement commands (run after opt_design, when the synthesized
        # netlist and its auto-derived generated clocks exist) rather than into
        # the .xdc, or Vivado drops them as "no valid object".
        pre = getattr(platform.toolchain, "pre_placement_commands", None)
        assert pre is not None, "Vivado toolchain required for HDMI-in timing constraints"

        # 1) The recovered HDMI clock family is asynchronous to the whole
        #    sys/DDR clock tree. Group *all* generated clocks of sys against
        #    *all* generated clocks of the HDMI-input port in one shot -- this
        #    covers every sys<->pix / sys<->pix1p25x_r / sys<->pix_raw crossing
        #    (freqmeter, the datacapture BusSynchronizers, the DRP handshake,
        #    the EDID MultiRegs). A single sys<->pix false-path is NOT enough:
        #    the datacapture control/status buses cross sys<->pix1p25x_r and the
        #    BusSynchronizer data path is not mr_ff-tagged, so it is not
        #    auto-false-pathed. Mirrors the 2019 design (netv2mvp.py:937).
        pre.append(
            "set_clock_groups -asynchronous "
            "-group [get_clocks -include_generated_clocks -of_objects [get_nets sys_clk]] "
            "-group [get_clocks -include_generated_clocks -of_objects [get_ports hdmi_in0_clk_p]]"
        )

        # 2) Serdes-to-fabric / gearbox handoffs *within* the HDMI clock family
        #    are related-clock crossings that rely on the MMCM keeping the legs
        #    phase aligned; they are timed as multicycle (data is stable for >1
        #    cycle), not false paths. These are the 2019 design's input-path
        #    exceptions (netv2mvp.py:951-962), retargeted to this build's
        #    auto-generated clock names via their clock-domain nets:
        #      pix1p25x   = the 8->10 gearbox input leg (BUFG /4)
        #      pix1p25x_r = the ISERDESE2 CLKDIV / delay-logic leg (BUFR /4)
        #      pix        = the pixel-clock fabric (BUFG /5)
        # Vivado auto-derives these generated clocks from the create_clock on
        # the input port and names them after the MMCM output nets: pix and
        # pix1p25x collapse onto main_mmcm_clk0 / main_mmcm_clk1 (the *_clk
        # nets are absorbed), while the BUFR leg keeps the net name
        # pix1p25x_r_clk. Reference them by clock name (glob) -- get_nets on the
        # absorbed pix/pix1p25x nets returns nothing at pre-placement.
        pix_clk     = "[get_clocks *mmcm_clk0]"
        pix125_clk  = "[get_clocks *mmcm_clk1]"
        pix125r_clk = "[get_clocks *pix1p25x_r_clk]"
        for _from, _to in ((pix125_clk, pix_clk),       # gearbox pix1p25x -> pix
                           (pix_clk, pix125_clk),       # gearbox reset/ctrl pix -> pix1p25x
                           (pix125r_clk, pix_clk),      # serdes leg  pix1p25x_r -> pix
                           (pix_clk, pix125r_clk)):      # pix -> serdes leg
            pre.append(f"set_multicycle_path 2 -setup -start -from {_from} -to {_to}")
            pre.append(f"set_multicycle_path 1 -hold -from {_from} -to {_to}")


def main():
    parser = LiteXArgumentParser(
        platform    = kosagi_netv2.Platform,
        description = "NeTV2 HDMI-input SoC (phase 7a): ported litevideo TERC4 input pipeline.",
    )
    parser.add_target_argument("--variant",      default="a7-100",
        help="Board variant (a7-35 or a7-100). Phase 7a targets a7-100.")
    parser.add_target_argument("--sys-clk-freq", default=100e6, type=float,
        help="System clock frequency.")
    args = parser.parse_args()

    soc = NeTV2HDMIInSoC(
        variant      = args.variant,
        sys_clk_freq = args.sys_clk_freq,
        **parser.soc_argdict,
    )

    builder_kwargs = parser.builder_argdict
    output_dir = builder_kwargs.get("output_dir") or DEFAULT_OUT
    builder_kwargs["output_dir"] = output_dir
    if not builder_kwargs.get("csr_csv"):
        builder_kwargs["csr_csv"] = os.path.join(output_dir, "csr.csv")

    builder = Builder(soc, **builder_kwargs)
    if args.build:
        # Full build: run the toolchain (Vivado) through to a bitstream.
        builder.build(**parser.toolchain_argdict)
    else:
        # Elaboration only: finalize the SoC and emit the gateware Verilog +
        # software headers without invoking the toolchain. This is the quick
        # "does it elaborate / generate Verilog cleanly" check.
        builder.build(**parser.toolchain_argdict, run=False)


if __name__ == "__main__":
    main()
